spring:
  application:
    name: Workly

  datasource:
    url: jdbc:postgresql://localhost:5432/worklydb
    username: postgres
    password: postgresql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true

api:
  jwt:
    token:
      secret: c0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1
      expiration: 3_600_000 # 1h in ms